version: '3.8'

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & celery -A app.tasks.celery_app.celery_app worker --loglevel=info"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"